version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"